version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: othello_imager
      POSTGRES_PASSWORD: "L7b187CoKN3z6z2UCB13PUp7RblRNA8l"
    volumes:
      - othello_imager_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "faCIs7nJExOIJl_vOJIJroQ5XnW-mdqo"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  othello_imager_data:
